a='*'
print('A------------------')
print(a)
print(a,a)
print(a,a,a)
print(a,a,a,a)
print('B----------------')
print(a,' ',a,' ',a,' ',a)
print(' ',a,' ',a,' ',a)
print(' '' ',a,' ',a,)
print(' '' '' ',a,' '' ')
print('C----------------')
print(a,a,a,a)
print(a,a,a)
print(a,a)
print(a)
print('D------------------')
print(' '' '' ',a)
print(' '' ',a,' ',a)
print(' ',a,' ',a,' ',a)
print(a,' ',a,' ',a,' ',a)